---
title: "Tour de France 2022 Fantasy sportif"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: spacelab
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, cache = FALSE)
```

```{r, include=FALSE}
library(tidyverse)
library(rvest)
library(polite)
library(tidyr)
library(kableExtra)
library(DT)

# Load in stage data

Stage_1 <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-1/result/result")
Sprint <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-1-points")
Stage_2 <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-2/result/result")
Stage_3 <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-3/result/result")
Stage_4 <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-4/result/result")
Stage_5 <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-5/result/result")
Stage_6 <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-6/result/result")
Stage_7 <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-7/result/result")
Stage_8 <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-8/result/result")
Stage_9 <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-9/result/result")
Stage_10 <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-10/result/result")
Stage_11 <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-11/result/result")
Stage_12 <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-12/result/result")
Stage_13 <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-13/result/result")
Stage_14 <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-14/result/result")
Stage_15 <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-15/result/result")
Stage_16 <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-16/result/result")
Stage_17 <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-17/result/result")
Stage_18 <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-18/result/result")
Stage_19 <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-19/result/result")
Stage_20 <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-20/result/result")
Stage_21 <- read_html("https://www.procyclingstats.com/race/tour-de-france/2022/stage-21/result/result")
  
# Get results

stage_1_results <- Stage_1 %>%
  html_node("table") %>% 
  html_table() %>% 
  as_tibble(.name_repair = "unique") %>% 
  select(Rnk, GC, BIB, Rider) %>% 
  mutate(Stage = 1,
         `Most combative` = "NO")

stage_2_results <- Stage_2 %>%
  html_node("table") %>% 
  html_table() %>% 
  as_tibble(.name_repair = "unique") %>% 
  select(Rnk, GC, BIB, Rider) %>% 
  mutate(Stage = 2,
         `Most combative` = if_else(BIB == 122, "YES", "NO"))

stage_3_results <- Stage_3 %>%
  html_node("table") %>% 
  html_table() %>% 
  as_tibble(.name_repair = "unique") %>% 
  select(Rnk, GC, BIB, Rider) %>% 
  mutate(Stage = 3,
         `Most combative` = if_else(BIB == 146, "YES", "NO"))

stage_4_results <- Stage_4 %>%
  html_node("table") %>% 
  html_table() %>% 
  as_tibble(.name_repair = "unique") %>% 
  select(Rnk, GC, BIB, Rider) %>% 
  mutate(Stage = 4,
         `Most combative` = if_else(BIB == 76, "YES", "NO"))

stage_5_results <- Stage_5 %>%
  html_node("table") %>% 
  html_table() %>% 
  as_tibble(.name_repair = "unique") %>% 
  select(Rnk, GC, BIB, Rider) %>% 
  mutate(Stage = 5,
         Rnk = recode(Rnk, DNF = "NA"),
         Rnk = as.numeric(Rnk),
         `Most combative` = if_else(BIB == 146, "YES", "NO"))

stage_6_results <- Stage_6 %>%
  html_node("table") %>% 
  html_table() %>% 
  as_tibble(.name_repair = "unique") %>% 
  select(Rnk, GC, BIB, Rider) %>% 
  mutate(Stage = 6,
         Rnk = recode(Rnk, DNF = "NA"),
         Rnk = as.numeric(Rnk),
         `Most combative` = if_else(BIB == 16, "YES", "NO"))

stage_7_results <- Stage_7 %>%
  html_node("table") %>% 
  html_table() %>% 
  as_tibble(.name_repair = "unique") %>% 
  select(Rnk, GC, BIB, Rider) %>% 
  mutate(Stage = 7)

stage_8_results <- Stage_8 %>%
  html_node("table") %>% 
  html_table() %>% 
  as_tibble(.name_repair = "unique") %>% 
  select(Rnk, GC, BIB, Rider) %>% 
  mutate(Stage = 8)

stage_9_results <- Stage_9 %>%
  html_node("table") %>% 
  html_table() %>% 
  as_tibble(.name_repair = "unique") %>% 
  select(Rnk, GC, BIB, Rider) %>% 
  mutate(Stage = 9)

stage_10_results <- Stage_10 %>%
  html_node("table") %>% 
  html_table() %>% 
  as_tibble(.name_repair = "unique") %>% 
  select(Rnk, GC, BIB, Rider) %>% 
  mutate(Stage = 10)

stage_11_results <- Stage_11 %>%
  html_node("table") %>% 
  html_table() %>% 
  as_tibble(.name_repair = "unique") %>% 
  select(Rnk, GC, BIB, Rider) %>% 
  mutate(Stage = 11)

stage_12_results <- Stage_12 %>%
  html_node("table") %>% 
  html_table() %>% 
  as_tibble(.name_repair = "unique") %>% 
  select(Rnk, GC, BIB, Rider) %>% 
  mutate(Stage = 12)

stage_13_results <- Stage_13 %>%
  html_node("table") %>% 
  html_table() %>% 
  as_tibble(.name_repair = "unique") %>% 
  select(Rnk, GC, BIB, Rider) %>% 
  mutate(Stage = 13)

stage_14_results <- Stage_14 %>%
  html_node("table") %>% 
  html_table() %>% 
  as_tibble(.name_repair = "unique") %>% 
  select(Rnk, GC, BIB, Rider) %>% 
  mutate(Stage = 14)

stage_15_results <- Stage_15 %>%
  html_node("table") %>% 
  html_table() %>% 
  as_tibble(.name_repair = "unique") %>% 
  select(Rnk, GC, BIB, Rider) %>% 
  mutate(Stage = 15)

stage_16_results <- Stage_16 %>%
  html_node("table") %>% 
  html_table() %>% 
  as_tibble(.name_repair = "unique") %>% 
  select(Rnk, GC, BIB, Rider) %>% 
  mutate(Stage = 16)

stage_17_results <- Stage_17 %>%
  html_node("table") %>% 
  html_table() %>% 
  as_tibble(.name_repair = "unique") %>% 
  select(Rnk, GC, BIB, Rider) %>% 
  mutate(Stage = 17)

stage_18_results <- Stage_18 %>%
  html_node("table") %>% 
  html_table() %>% 
  as_tibble(.name_repair = "unique") %>% 
  select(Rnk, GC, BIB, Rider) %>% 
  mutate(Stage = 18)

stage_19_results <- Stage_19 %>%
  html_node("table") %>% 
  html_table() %>% 
  as_tibble(.name_repair = "unique") %>% 
  select(Rnk, GC, BIB, Rider) %>% 
  mutate(Stage = 19)

stage_20_results <- Stage_20 %>%
  html_node("table") %>% 
  html_table() %>% 
  as_tibble(.name_repair = "unique") %>% 
  select(Rnk, GC, BIB, Rider) %>% 
  mutate(Stage = 20)

stage_21_results <- Stage_21 %>%
  html_node("table") %>% 
  html_table() %>% 
  as_tibble(.name_repair = "unique") %>% 
  select(Rnk, GC, BIB, Rider) %>% 
  mutate(Stage = 21)

Stage_list <- list(stage_1_results, stage_2_results, stage_3_results, stage_4_results, stage_5_results, stage_6_results)
                   # stage_7_results, stage_8_results, stage_9_results, stage_10_results, stage_11_results, stage_12_results, stage_13_results, stage_14_results,
                  # stage_15_results, stage_16_results, stage_17_results, stage_18_results,
                  # stage_19_results, stage_20_results, stage_21_results)
```

# Starting Lineups

$~$

```{r}
Teams <- tibble(`Rider type` = c("General", "General", "General", "General", "Sprinter", "Sub"),
                Stiff = c("Pogačar Tadej", "Hirschi Marc", "Woods Michael", "Ciccone Giulio", "Philipsen Jasper", "Haig Jack"),
                Willo = c("Roglič Primož", "Thomas Geraint", "Caruso Damiano", "Fuglsang Jakob", "Groenewegen Dylan", "Pidcock Thomas"),
                Falcs = c("Vingegaard Jonas", "Pedersen Mads", "Bardet Romain", "Ganna Fillipo", "Ewan Caleb", "Yates Adam"),
                Haz = c("van Aert Wout", "O'Connor Ben", "Martin Guillaume", "Mohorič Matej", "Sagan Peter", "Lutsenko Alexey"),
                Zing = c("Martínez Daniel Felipe", "Pinot Thibaut", "Mas Enric", "Guerreiro Ruben", "van der Poel Mathieu", "Quintana Nairo"),
                Bergs = c("Vlasov Alexandr", "Urán Rigoberto", "Gaudu David", "Matthews Michael", "Jakobsen Fabio", "Kuss Sepp")) 

# For the standings

startlist <- read_csv("Riders.csv") %>% 
  mutate(`Sub activated` = if_else(Ridername == "Hirschi Marc", "6", "NO")) 
  


# Who has who?

#Teams %>% 
 # kbl() %>% 
  #kable_minimal() %>% 
 # column_spec(8, background = spec_color(data$`DIFFERENCE RANK`, option = "A", begin = 0.6, end = 0.95))
  
Teams %>%
  mutate(Stiff = cell_spec(Stiff, "html", strikeout = ifelse(Stiff == "Haig Jack", TRUE, FALSE))) %>% 
  kable(escape = F) %>% 
  kable_styling() %>% 
  #row_spec(5, color = "black", background = "#89c0b6") %>% 
   row_spec(6, background = "#f97b57") %>% 
  column_spec(1, bold = TRUE)
  
```

$~$

# Provisional standings

$~$

```{r}
  
Stage_Scoring <- function(stage_data){
  stage_data %>%
  mutate(stage_points = recode(Rnk, "1" = 10, "2" = 6, "3" = 4, .default = 0),
         GC_points = recode(GC, "1" = 25, "2" = 22, "3" = 20,
                            "4" = 18, "5" = 16, "6" = 14, "7" = 14,
                            "8" = 12, "9" = 10, "10" = 10, "11" = 8,
                            "12" = 8, "13" = 6, "14" = 6, "15" = 6, .default = 0),
         `Most combative points` = if_else(`Most combative` == "YES", 10, 0))
}

Total_score <- map_dfr(Stage_list, Stage_Scoring) 

Total_score_tidy <- Total_score %>% 
  group_by(Rider) %>% 
  mutate(Total_stage_points = sum(stage_points, na.rm = TRUE),
         Total_most_combative_points = sum(`Most combative points`, na.rm = TRUE)) %>% 
  distinct(BIB, .keep_all = TRUE)

a <- 
  Total_score_tidy %>%
  select(Rider, BIB, Total_stage_points, Total_most_combative_points)

b <-
  Total_score %>% 
  filter(Stage == max(Stage)) %>%
  select(GC, BIB, Rider, GC_points)

Results <- 
  left_join(a, b) %>% 
  mutate(GC_points = replace_na(GC_points, 0),
         GC = replace_na(GC, "DNF"), 
         Final_score = Total_stage_points + GC_points + Total_most_combative_points) %>% 
  arrange(-Final_score) %>% 
  select(Rider, BIB, GC, Total_stage_points, Total_most_combative_points, GC_points, Final_score)

Results_complete <- left_join(startlist, Results) %>% 
  select(-c(Rider))

Team_rankings <-
  Results_complete %>%
  filter(Sub == "NO") %>% # fix this so sub activates
  group_by(Picked_by) %>% 
  mutate(`Provisional score` = sum(Final_score),
         `Confirmed points` = sum(Total_stage_points) + sum(Total_most_combative_points)) %>% 
  arrange(-`Provisional score`) %>% 
  distinct(Picked_by, .keep_all = TRUE) %>% 
  select(Picked_by, `Confirmed points`, `Provisional score`) %>% 
  filter(Picked_by  != "Not selected") %>% 
  rename(`Directeur sportif` = Picked_by)

Rider_rankings <-
  Results_complete %>% 
  arrange(-Final_score) %>% 
  rename(`Provisional score` = Final_score) %>% 
  rename(`Directeur sportif` = Picked_by,
         Rider = Ridername, 
         `Cumulative stage points` = Total_stage_points,
         `Cumulative most combative points` = Total_most_combative_points,
         `GC points` = GC_points) %>% 
  select(-c(BIB))

```

```{r}
Team_rankings %>% 
  kable() %>% 
  kable_styling()
```

$~$

# Rider rankings

$~$

```{r}
# Create a function to build HTML searchable tables

my_data_table <- function(df){
  datatable(
    df, rownames=FALSE,
    autoHideNavigation = TRUE,
    extensions = c("Scroller",  "Buttons"),
    options = list(
      dom = 'Bfrtip',
      deferRender=TRUE,
      scrollX=TRUE, scrollY=400,
      scrollCollapse=TRUE,
      buttons =
        list('pageLength', 'colvis', 'csv', list(
          extend = 'pdf',
          pageSize = 'A4',
          orientation = 'landscape',
          filename = 'tour_data')),
      pageLength = 200
    )
  )
}

my_data_table(Rider_rankings %>% 
                select(Rider, `Directeur sportif`, `Provisional score`,
                       `GC points`, `Cumulative stage points`, `Cumulative most combative points`))


```

$~$

# Stage results {.tabset .tabset-pills}

## Stage 1

```{r}
  
kable(Stage_Scoring(stage_1_results) %>%
        rename(`Stage result` = Rnk,
               `Stage points` = stage_points) %>% 
                select(Rider, `Stage result`, `Stage points`)) %>% 
  kable_styling()
  
```

## Stage 2

```{r}
  
kable(Stage_Scoring(stage_2_results) %>% 
               rename(`Stage result` = Rnk,                `Stage points` = stage_points) %>%                  select(Rider, `Stage result`, `Stage points`)) %>% 
  kable_styling()
  
```

## Stage 3

```{r}
  
kable(Stage_Scoring(stage_3_results) %>% 
               rename(`Stage result` = Rnk,                `Stage points` = stage_points) %>%                  select(Rider, `Stage result`, `Stage points`)) %>% 
  kable_styling()
  
```

## Stage 4

```{r}
  
kable(Stage_Scoring(stage_4_results) %>% 
               rename(`Stage result` = Rnk,                `Stage points` = stage_points) %>%                  select(Rider, `Stage result`, `Stage points`)) %>% 
  kable_styling()
  
```

## Stage 5

```{r}
  
kable(Stage_Scoring(stage_5_results) %>% 
               rename(`Stage result` = Rnk,                `Stage points` = stage_points) %>%                  select(Rider, `Stage result`, `Stage points`)) %>% 
  kable_styling()
  
```

## Stage 6

```{r}
  
kable(Stage_Scoring(stage_6_results) %>% 
               rename(`Stage result` = Rnk,                `Stage points` = stage_points) %>%                  select(Rider, `Stage result`, `Stage points`)) %>% 
  kable_styling()
  
```

## Stage 7

```{r, eval = FALSE}
  
kable(Stage_Scoring(stage_7_results) %>% 
               rename(`Stage result` = Rnk,                `Stage points` = stage_points) %>%                  select(Rider, `Stage result`, `Stage points`)) %>% 
  kable_styling()
  
```

## Stage 8

```{r, eval = FALSE}
  
kable(Stage_Scoring(stage_8_results) %>% 
               rename(`Stage result` = Rnk,                `Stage points` = stage_points) %>%                  select(Rider, `Stage result`, `Stage points`)) %>% 
  kable_styling()
  
```

## Stage 9

```{r, eval = FALSE}
  
kable(Stage_Scoring(stage_9_results) %>% 
               rename(`Stage result` = Rnk,                `Stage points` = stage_points) %>%                  select(Rider, `Stage result`, `Stage points`)) %>% 
  kable_styling()
  
```

## Stage 10

```{r, eval = FALSE}
  
kable(Stage_Scoring(stage_10_results) %>% 
               rename(`Stage result` = Rnk,                `Stage points` = stage_points) %>%                  select(Rider, `Stage result`, `Stage points`)) %>% 
  kable_styling()
  
```

## Stage 11

```{r, eval = FALSE}
  
kable(Stage_Scoring(stage_11_results) %>% 
               rename(`Stage result` = Rnk,                `Stage points` = stage_points) %>%                  select(Rider, `Stage result`, `Stage points`)) %>% 
  kable_styling()
  
```

## Stage 12

```{r, eval = FALSE}
  
kable(Stage_Scoring(stage_12_results) %>% 
               rename(`Stage result` = Rnk,                `Stage points` = stage_points) %>%                  select(Rider, `Stage result`, `Stage points`)) %>% 
  kable_styling()
  
```

## Stage 13

```{r, eval = FALSE}
  
kable(Stage_Scoring(stage_13_results) %>% 
               rename(`Stage result` = Rnk,                `Stage points` = stage_points) %>%                  select(Rider, `Stage result`, `Stage points`)) %>% 
  kable_styling()
  
```

## Stage 14

```{r, eval = FALSE}
  
kable(Stage_Scoring(stage_14_results) %>% 
               rename(`Stage result` = Rnk,                `Stage points` = stage_points) %>%                  select(Rider, `Stage result`, `Stage points`)) %>% 
  kable_styling()
  
```

## Stage 15

```{r, eval = FALSE}
  
kable(Stage_Scoring(stage_15_results) %>% 
               rename(`Stage result` = Rnk,                `Stage points` = stage_points) %>%                  select(Rider, `Stage result`, `Stage points`)) %>% 
  kable_styling()
  
```

## Stage 16

```{r, eval = FALSE}
  
kable(Stage_Scoring(stage_16_results) %>% 
               rename(`Stage result` = Rnk,                `Stage points` = stage_points) %>%                  select(Rider, `Stage result`, `Stage points`)) %>% 
  kable_styling()
  
```

## Stage 17

```{r, eval = FALSE}
  
kable(Stage_Scoring(stage_17_results) %>% 
               rename(`Stage result` = Rnk,                `Stage points` = stage_points) %>%                  select(Rider, `Stage result`, `Stage points`)) %>% 
  kable_styling()
  
```

## Stage 18

```{r, eval = FALSE}
  
kable(Stage_Scoring(stage_18_results) %>% 
               rename(`Stage result` = Rnk,                `Stage points` = stage_points) %>%                  select(Rider, `Stage result`, `Stage points`)) %>% 
  kable_styling()
  
```

## Stage 19

```{r, eval = FALSE}
  
kable(Stage_Scoring(stage_19_results) %>% 
               rename(`Stage result` = Rnk,                `Stage points` = stage_points) %>%                  select(Rider, `Stage result`, `Stage points`)) %>% 
  kable_styling()
  
```

## Stage 20

```{r, eval = FALSE}
  
kable(Stage_Scoring(stage_20_results) %>% 
               rename(`Stage result` = Rnk,                `Stage points` = stage_points) %>%                  select(Rider, `Stage result`, `Stage points`)) %>% 
  kable_styling()
  
```

## Stage 21

```{r, eval = FALSE}
  
kable(Stage_Scoring(stage_21_results) %>% 
               rename(`Stage result` = Rnk,                `Stage points` = stage_points) %>%                  select(Rider, `Stage result`, `Stage points`)) %>% 
  kable_styling()
  
```

$~$

# The Scoring system

**Stage**

1st = 10

2nd = 6

3rd = 4

**GC**

1st = 25

2nd = 22

3rd = 20

4th = 18

5th = 16

6-7th = 14

8th = 12

9-10th = 10

11-12th = 8

13-15th = 6

**Green jersey**

1st = 10

2nd = 8

3rd = 6

**KOM jersey**

1st = 10

2nd = 6

3rd = 4

**Most combative**

1st on each stage = 10
